#!/bin/bash

# Binary LED counter for Raspberry Pi

#GPIO_PINS='0 1 4 7 8 9 10 11 14 15 17 18 21 22 23 24 25'
# Uncomment the following line for Raspberry Pi Revision 2
GPIO_PINS='29 28 27 26'
pins=2
delay=1

# Initialize pins
for ((pin = 0; pin < pins; pin++)); do
    gpio mode $pin out
    gpio write $pin 0
done
